name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: machine1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t hellopradum/backend-wanderlust backend/.
          docker build -t hellopradum/frontend-wanderlust frontend/.
          
          docker push hellopradum/backend-wanderlust:latest
          docker push hellopradum/frontend-wanderlust:latest

